---
theme: jekyll-theme-slate
title: Wellcome to brnfra's homepage!
description: Writing some tutorials and wikis
url: https://brnfra.github.io  
repository: https://github.com/brnfra
timezone: America/Bahia
markdown: kramdown

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" 
    values:
      layout: "default"
      author: "Bruno Franco"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
